import { Schema, model } from "mongoose";
import {
  IProjectLanding,
  LANDING_SECTIONS,
} from "./projectLanding.interface";

const mediaRef = { type: Schema.Types.ObjectId, ref: "Media" };

const sectionFlag = {
  visible: { type: Boolean, default: true },
};

const sectionsShape = Object.fromEntries(
  LANDING_SECTIONS.map((key) => [key, sectionFlag]),
);

const projectLandingSchema = new Schema<IProjectLanding>(
  {
    project: {
      type: Schema.Types.ObjectId,
      ref: "Project",
      required: true,
      unique: true,
      index: true,
    },
    path: {
      type: String,
      required: true,
      trim: true,
      lowercase: true,
    },
    isActive: { type: Boolean, default: true, index: true },
    facebookUrl: { type: String, trim: true },
    phonePrimary: { type: String, trim: true },
    phoneSecondary: { type: String, trim: true },
    whatsapp: { type: String, trim: true },
    metaTitle: { type: String, trim: true },
    metaTitleBn: { type: String, trim: true },
    metaDescription: { type: String, trim: true },
    metaDescriptionBn: { type: String, trim: true },
    navEnquire: { type: String, trim: true },
    navEnquireBn: { type: String, trim: true },
    sections: { type: sectionsShape, default: () => ({}) },
    hero: {
      image: mediaRef,
      badge: String,
      badgeBn: String,
      handover: String,
      handoverBn: String,
      eyebrow: String,
      eyebrowBn: String,
      title: String,
      titleBn: String,
      lead: String,
      leadBn: String,
      location: String,
      locationBn: String,
      ctaPrimary: String,
      ctaPrimaryBn: String,
      ctaSecondary: String,
      ctaSecondaryBn: String,
      stats: {
        type: [
          {
            value: String,
            valueBn: String,
            label: String,
            labelBn: String,
            icon: String,
            _id: false,
          },
        ],
        default: [],
      },
    },
    about: {
      image: mediaRef,
      eyebrow: String,
      eyebrowBn: String,
      title: String,
      titleBn: String,
      body: String,
      bodyBn: String,
      points: {
        type: [
          {
            title: String,
            titleBn: String,
            body: String,
            bodyBn: String,
            icon: String,
            _id: false,
          },
        ],
        default: [],
      },
    },
    residences: {
      images: { type: [mediaRef], default: [] },
      eyebrow: String,
      eyebrowBn: String,
      title: String,
      titleBn: String,
      description: String,
      descriptionBn: String,
      featured: String,
      featuredBn: String,
      cta: String,
      ctaBn: String,
      preview: String,
      previewBn: String,
      close: String,
      closeBn: String,
      unit: {
        name: String,
        nameBn: String,
        beds: String,
        bedsBn: String,
        baths: String,
        bathsBn: String,
        size: String,
        sizeBn: String,
        price: String,
        priceBn: String,
        note: String,
        noteBn: String,
      },
      highlights: {
        type: [
          {
            label: String,
            labelBn: String,
            value: String,
            valueBn: String,
            icon: String,
            _id: false,
          },
        ],
        default: [],
      },
    },
    elevation: {
      eyebrow: String,
      eyebrowBn: String,
      title: String,
      titleBn: String,
      description: String,
      descriptionBn: String,
      preview: String,
      previewBn: String,
      close: String,
      closeBn: String,
      views: {
        type: [
          {
            label: String,
            labelBn: String,
            hint: String,
            hintBn: String,
            image: mediaRef,
            _id: false,
          },
        ],
        default: [],
      },
    },
    films: {
      eyebrow: String,
      eyebrowBn: String,
      title: String,
      titleBn: String,
      description: String,
      descriptionBn: String,
      play: String,
      playBn: String,
      items: {
        type: [
          {
            title: String,
            titleBn: String,
            caption: String,
            captionBn: String,
            url: String,
            poster: mediaRef,
            provider: { type: String, enum: ["facebook", "youtube"], default: "youtube" },
            _id: false,
          },
        ],
        default: [],
      },
    },
    amenities: {
      eyebrow: String,
      eyebrowBn: String,
      title: String,
      titleBn: String,
      description: String,
      descriptionBn: String,
      items: {
        type: [
          {
            title: String,
            titleBn: String,
            body: String,
            bodyBn: String,
            icon: String,
            mapUrl: String,
            distance: String,
            distanceBn: String,
            _id: false,
          },
        ],
        default: [],
      },
    },
    gallery: {
      eyebrow: String,
      eyebrowBn: String,
      title: String,
      titleBn: String,
      open: String,
      openBn: String,
      close: String,
      closeBn: String,
      shots: {
        type: [
          {
            label: String,
            labelBn: String,
            image: mediaRef,
            _id: false,
          },
        ],
        default: [],
      },
    },
    location: {
      eyebrow: String,
      eyebrowBn: String,
      title: String,
      titleBn: String,
      description: String,
      descriptionBn: String,
      mapOpen: String,
      mapOpenBn: String,
      mapHint: String,
      mapHintBn: String,
      mapEmbedUrl: String,
      mapLinkUrl: String,
      facts: {
        type: [
          {
            label: String,
            labelBn: String,
            value: String,
            valueBn: String,
            _id: false,
          },
        ],
        default: [],
      },
    },
    process: {
      eyebrow: String,
      eyebrowBn: String,
      title: String,
      titleBn: String,
      steps: {
        type: [
          {
            title: String,
            titleBn: String,
            body: String,
            bodyBn: String,
            _id: false,
          },
        ],
        default: [],
      },
    },
    cta: {
      eyebrow: String,
      eyebrowBn: String,
      title: String,
      titleBn: String,
      description: String,
      descriptionBn: String,
      primary: String,
      primaryBn: String,
      call: String,
      callBn: String,
      whatsapp: String,
      whatsappBn: String,
    },
    reviews: {
      eyebrow: String,
      eyebrowBn: String,
      title: String,
      titleBn: String,
      description: String,
      descriptionBn: String,
      play: String,
      playBn: String,
      close: String,
      closeBn: String,
      items: {
        type: [
          {
            name: String,
            nameBn: String,
            role: String,
            roleBn: String,
            quote: String,
            quoteBn: String,
            avatar: mediaRef,
            poster: mediaRef,
            videoUrl: String,
            _id: false,
          },
        ],
        default: [],
      },
    },
    faq: {
      eyebrow: String,
      eyebrowBn: String,
      title: String,
      titleBn: String,
      description: String,
      descriptionBn: String,
      items: {
        type: [
          {
            question: String,
            questionBn: String,
            answer: String,
            answerBn: String,
            _id: false,
          },
        ],
        default: [],
      },
    },
    enquire: {
      eyebrow: String,
      eyebrowBn: String,
      title: String,
      titleBn: String,
      description: String,
      descriptionBn: String,
      phoneLabel: String,
      phoneLabelBn: String,
      whatsappLabel: String,
      whatsappLabelBn: String,
      source: String,
      form: {
        name: String,
        nameBn: String,
        namePlaceholder: String,
        namePlaceholderBn: String,
        phone: String,
        phoneBn: String,
        email: String,
        emailBn: String,
        plan: String,
        planBn: String,
        message: String,
        messageBn: String,
        messagePlaceholder: String,
        messagePlaceholderBn: String,
        submit: String,
        submitBn: String,
        submitting: String,
        submittingBn: String,
        privacy: String,
        privacyBn: String,
        successTitle: String,
        successTitleBn: String,
        successBody: String,
        successBodyBn: String,
      },
    },
    custom: {
      eyebrow: String,
      eyebrowBn: String,
      title: String,
      titleBn: String,
      body: String,
      bodyBn: String,
    },
    createdBy: { type: Schema.Types.ObjectId, ref: "User" },
    updatedBy: { type: Schema.Types.ObjectId, ref: "User" },
  },
  { timestamps: true },
);

projectLandingSchema.index({ path: 1 }, { unique: true });

export const ProjectLanding = model<IProjectLanding>(
  "ProjectLanding",
  projectLandingSchema,
);
